DIG-2164 Content Author Notifications
CityOfBoston/boston.gov-d8 pull request #3109
Opened 2023-06-07 18:35 UTC by subaha-cob

DIG-2164 Content Author Notifications

2023-06-07 18:49 UTC, davidrkupton requested changes

2023-06-07 18:49 UTC, davidrkupton commented on config/default/user.role.content_author.yml
Are you sure you want content authors (this can be almost any COB employee) to be able to administer this module?

2023-06-07 18:49 UTC, davidrkupton commented on config/default/user.role.content_reviewer.yml
ditto: Are you sure you want content reviewers to be able to administer this module?

2023-06-07 18:49 UTC, davidrkupton commented on config/default/core.extension.yml
We do not want to enable all those modules by default. I think the only addition in this file should be line 34.

2023-06-08 17:57 UTC, subaha-cob commented on config/default/core.extension.yml
Revert changes

2023-06-08 17:59 UTC, davidrkupton approved these changes
LGTM!

2023-06-08 18:43 UTC, merged